name: Build
on:
  push:
    branches:
      - 'master'
jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Build with Maven
      run: mvn clean package --batch-mode --quiet
    - name: Run Application
      run: mvn spring-boot:run &
  build_on_mac:
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Build with Maven
      run: mvn clean package --batch-mode --quiet
    - name: Run Application
      run: mvn spring-boot:run &
  build_on_windows:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Build with Maven
      run: mvn clean package --batch-mode --quiet
    - name: Run Application
      run: mvn spring-boot:run &
